services:
  api:
    container_name: dev-simple-inventory-api
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    volumes:
      - ./src/backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - APP_VERSION=${VERSION}
    networks:
      - internal
    ports:
      - 3001:80
    restart: unless-stopped
  frontend:
    container_name: dev-simple-inventory-frontend
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    depends_on:
      - api
    networks:
      - internal
    restart: unless-stopped
  db:
    container_name: dev-simple-inventory-db
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - internal
  # only for development
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 82:8080
    networks:
      - internal
networks:
  internal:
volumes:
  dbdata: